//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peygir.Presentation.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peygir.Presentation.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Add {
            get {
                object obj = ResourceManager.GetObject("Image_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Attachment {
            get {
                object obj = ResourceManager.GetObject("Image_Attachment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Cancel {
            get {
                object obj = ResourceManager.GetObject("Image_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Change {
            get {
                object obj = ResourceManager.GetObject("Image_Change", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Close {
            get {
                object obj = ResourceManager.GetObject("Image_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Delete {
            get {
                object obj = ResourceManager.GetObject("Image_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Edit {
            get {
                object obj = ResourceManager.GetObject("Image_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Exit {
            get {
                object obj = ResourceManager.GetObject("Image_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Help {
            get {
                object obj = ResourceManager.GetObject("Image_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_History {
            get {
                object obj = ResourceManager.GetObject("Image_History", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_New {
            get {
                object obj = ResourceManager.GetObject("Image_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_OK {
            get {
                object obj = ResourceManager.GetObject("Image_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Open {
            get {
                object obj = ResourceManager.GetObject("Image_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Options {
            get {
                object obj = ResourceManager.GetObject("Image_Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Peygir {
            get {
                object obj = ResourceManager.GetObject("Image_Peygir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save {
            get {
                object obj = ResourceManager.GetObject("Image_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_SaveAs {
            get {
                object obj = ResourceManager.GetObject("Image_SaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Show {
            get {
                object obj = ResourceManager.GetObject("Image_Show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string String_Accepted {
            get {
                return ResourceManager.GetString("String_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected attachment(s)?.
        /// </summary>
        internal static string String_AreYouSureYouWantToDeleteAttachments {
            get {
                return ResourceManager.GetString("String_AreYouSureYouWantToDeleteAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected milestone(s) and its (their) tickets?.
        /// </summary>
        internal static string String_AreYouSureYouWantToDeleteSelectedMilestonesAndTheirTickets {
            get {
                return ResourceManager.GetString("String_AreYouSureYouWantToDeleteSelectedMilestonesAndTheirTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected project(s) and its (their) milestones and tickets?.
        /// </summary>
        internal static string String_AreYouSureYouWantToDeleteSelectedProjects {
            get {
                return ResourceManager.GetString("String_AreYouSureYouWantToDeleteSelectedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected ticket(s)?.
        /// </summary>
        internal static string String_AreYouSureYouWantToDeleteSelectedTickets {
            get {
                return ResourceManager.GetString("String_AreYouSureYouWantToDeleteSelectedTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Assigned to&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_AssignedToChangesFromXToY {
            get {
                return ResourceManager.GetString("String_AssignedToChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocker.
        /// </summary>
        internal static string String_Blocker {
            get {
                return ResourceManager.GetString("String_Blocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string String_Closed {
            get {
                return ResourceManager.GetString("String_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string String_Completed {
            get {
                return ResourceManager.GetString("String_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string String_Critical {
            get {
                return ResourceManager.GetString("String_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: {0}.
        /// </summary>
        internal static string String_DatabaseX {
            get {
                return ResourceManager.GetString("String_DatabaseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        internal static string String_Defect {
            get {
                return ResourceManager.GetString("String_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attachments.
        /// </summary>
        internal static string String_DeleteAttachments {
            get {
                return ResourceManager.GetString("String_DeleteAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete milestones.
        /// </summary>
        internal static string String_DeleteMilestones {
            get {
                return ResourceManager.GetString("String_DeleteMilestones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete projects.
        /// </summary>
        internal static string String_DeleteProjects {
            get {
                return ResourceManager.GetString("String_DeleteProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tickets.
        /// </summary>
        internal static string String_DeleteTickets {
            get {
                return ResourceManager.GetString("String_DeleteTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Description&quot; changes..
        /// </summary>
        internal static string String_DescriptionChanges {
            get {
                return ResourceManager.GetString("String_DescriptionChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string String_Error {
            get {
                return ResourceManager.GetString("String_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Request.
        /// </summary>
        internal static string String_FeatureRequest {
            get {
                return ResourceManager.GetString("String_FeatureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string String_High {
            get {
                return ResourceManager.GetString("String_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        internal static string String_Highest {
            get {
                return ResourceManager.GetString("String_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string String_Low {
            get {
                return ResourceManager.GetString("String_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        internal static string String_Lowest {
            get {
                return ResourceManager.GetString("String_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string String_Major {
            get {
                return ResourceManager.GetString("String_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Milestone&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_MilestoneChangesFromXToY {
            get {
                return ResourceManager.GetString("String_MilestoneChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        internal static string String_Minor {
            get {
                return ResourceManager.GetString("String_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string String_New {
            get {
                return ResourceManager.GetString("String_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string String_Normal {
            get {
                return ResourceManager.GetString("String_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a milestone before adding a ticket..
        /// </summary>
        internal static string String_PleaseAddAMilestoneBeforeAddingATicket {
            get {
                return ResourceManager.GetString("String_PleaseAddAMilestoneBeforeAddingATicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a milestone..
        /// </summary>
        internal static string String_PleaseSelectAMilestone {
            get {
                return ResourceManager.GetString("String_PleaseSelectAMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify milestone state..
        /// </summary>
        internal static string String_PleaseSpecifyMilestoneState {
            get {
                return ResourceManager.GetString("String_PleaseSpecifyMilestoneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify ticket priority..
        /// </summary>
        internal static string String_PleaseSpecifyTicketPriority {
            get {
                return ResourceManager.GetString("String_PleaseSpecifyTicketPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify ticket severity..
        /// </summary>
        internal static string String_PleaseSpecifyTicketSeverity {
            get {
                return ResourceManager.GetString("String_PleaseSpecifyTicketSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify ticket state..
        /// </summary>
        internal static string String_PleaseSpecifyTicketState {
            get {
                return ResourceManager.GetString("String_PleaseSpecifyTicketState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify ticket type..
        /// </summary>
        internal static string String_PleaseSpecifyTicketType {
            get {
                return ResourceManager.GetString("String_PleaseSpecifyTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Priority&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_PriorityChangesFromXToY {
            get {
                return ResourceManager.GetString("String_PriorityChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Reported by&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_ReportedByChangesFromXToY {
            get {
                return ResourceManager.GetString("String_ReportedByChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Severity&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_SeverityChangesFromXToY {
            get {
                return ResourceManager.GetString("String_SeverityChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;State&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_StateChangesFromXToY {
            get {
                return ResourceManager.GetString("String_StateChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Summary&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_SummaryChangesFromXToY {
            get {
                return ResourceManager.GetString("String_SummaryChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string String_Task {
            get {
                return ResourceManager.GetString("String_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The milestone name cannot be blank..
        /// </summary>
        internal static string String_TheMilestoneNameCannotBeBlank {
            get {
                return ResourceManager.GetString("String_TheMilestoneNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project name cannot be blank..
        /// </summary>
        internal static string String_TheProjectNameCannotBeBlank {
            get {
                return ResourceManager.GetString("String_TheProjectNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ticket description cannot be blank..
        /// </summary>
        internal static string String_TheTicketDescriptionCannotBeBlank {
            get {
                return ResourceManager.GetString("String_TheTicketDescriptionCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ticket summary cannot be blank..
        /// </summary>
        internal static string String_TheTicketSummaryCannotBeBlank {
            get {
                return ResourceManager.GetString("String_TheTicketSummaryCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Ticket created..
        /// </summary>
        internal static string String_TicketCreated {
            get {
                return ResourceManager.GetString("String_TicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivial.
        /// </summary>
        internal static string String_Trivial {
            get {
                return ResourceManager.GetString("String_Trivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * &quot;Type&quot; changes from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string String_TypeChangesFromXToY {
            get {
                return ResourceManager.GetString("String_TypeChangesFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string String_Version {
            get {
                return ResourceManager.GetString("String_Version", resourceCulture);
            }
        }
	}
}
